version: "3.9"

services:
  postgres:
    image: docker.io/postgres:18
    container_name: financial-transactions-postgres
    environment:
      POSTGRES_DB: financial-transactions-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: docker.io/dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

  financial-transactions-ms:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    container_name: financial-transactions-ms
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/financial-transactions-db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  pgadmin_data: