spring:
  application:
    name: financial-transaction-ms

  server:
    port: 8080

  flyway:
    enabled: true

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/financial-transactions-db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    url: /openapi.yaml
    enabled: true


