create table accounts (
                          id bigint generated by default as identity,
                          number varchar(255),
                          external_id varchar(255) unique,
                          primary key (id)
);

create table customers (
                           account_id bigint unique,
                           id bigint generated by default as identity,
                           document_number varchar(255),
                           external_id varchar(255) unique,
                           primary key (id)
);

create table transactions (
                              amount numeric(38,2),
                              date_time timestamp(6),
                              id bigint generated by default as identity,
                              account_id bigint not null,
                              operation_type_id int not null,
                              external_id varchar(255) unique,
                              primary key (id)
);

create table operation_types (
                                 id bigint,
                                 description varchar(255) unique not null,
                                 primary key (id)
);

alter table if exists customers
    add constraint customer_account_fk
    foreign key (account_id)
    references accounts;

alter table if exists transactions
    add constraint transactions_operation_types_fk
    foreign key (operation_type_id)
    references operation_types;