create table accounts (
                          id bigint generated by default as identity,
                          number varchar(255),
                          uuid varchar(255) unique,
                          primary key (id)
);

create table customers (
                           account_id bigint unique,
                           id bigint generated by default as identity,
                           document_number varchar(255),
                           uuid varchar(255) unique,
                           primary key (id)
);

create table transactions (
                              amount numeric(38,2),
                              date_time timestamp(6),
                              id bigint generated by default as identity,
                              account_uuid varchar(255),
                              operation_type varchar(255) check ((operation_type in ('NORMAL_PURCHASE','PURCHASE_WITH_INSTALLMENTS','WITHDRAW','CREDIT_VOUCHER'))),
                              uuid varchar(255) unique,
                              primary key (id)
);

alter table if exists customers
    add constraint FKor0fx9fttvasr4grtaqnltyrl
    foreign key (account_id)
    references accounts;
